### ISSUE TITLE
Dark mode setting is ignored

### ISSUE THREAD

**Issue by Botspot** [openstreamorg/openstreammusic#2]
Initial launch asked if I wanted dark mode. I chose to enable dark mode, and it worked as intended. So far so good.

Then I clicked the gear button and then tried to switch to light mode and then back to dark mode. Now, no matter what I choose and then click Save, the main UI is always displayed in light mode. Even if I choose dark mode and then close the app, when I reopen it, the setting choice will change to light mode.

**Comment by techguy16** [comment]
That was fixed in 1.3, are you using 1.2?

**Comment by Botspot** [comment]
I am using 1.3.

**Comment by techguy16** [comment]
_Fixed in 1.3.1 - Not updating for Pi-Apps yet. Still yet to fix bugs._
